// Module included in the following assemblies:
// * serverless-logic/serverless-logic-upgrading-operator-from-1-37-0-to-1-37-1

:_mod-docs-content-type: REFERENCE
[id="serverless-logic-1-37-1-finalizing-the-upgrade_{context}"]
= Finalizing the upgrade

After upgrading the {ServerlessLogicOperatorName} to version 1.37.1, you must finalize the upgrade process by restoring or scaling workflows and cleaning up old services. This ensures that your system runs cleanly on the new version and that all dependent components are configured correctly.

Follow the appropriate steps below based on the profile of your workflows and services.

.Prerequisites
* You have access to the cluster with `cluster-admin` privileges.
* You have {ServerlessLogicOperatorName} installed on your cluster.
* You have access to a {ServerlessLogicProductName} project with the appropriate roles and permissions to create applications and other workloads in {ocp-product-title}.
* You have installed the OpenShift CLI (`oc`).
