// Module included in the following assemblies:
// * about/serverless-logic-overview.adoc


:_content-type: CONCEPT
[id="serverless-logic-overview-callbacks_{context}"]
= Callbacks

The Callback state performs an action and waits for an event, to be produced as a result of the action, to resume the workflow. The action peformed by a `Callback` state is an asynchronous external service invocation. Therefore, the Callback state is suitable to perform `fire&wait-for-result` operations.

From a workflow perspective, asynchronous service indicates that the control is returned to the caller immediately without waiting for the action to be completed. Once the action is completed, a CloudEvent is published to resume the workflow.

.Example of Callback state in JSON format 
[source, json]
----
{
        "name": "CheckCredit",
        "type": "callback",
        "action": {
            "functionRef": {
                "refName": "callCreditCheckMicroservice",
                "arguments": {
                    "customer": "${ .customer }"
                }
            }
        },
        "eventRef": "CreditCheckCompletedEvent",
        "timeouts": {
          "stateExecTimeout": "PT15M"
        },
        "transition": "EvaluateDecision"
}
----

.Example of Callback state in YAML format 
[source, yaml]
----
name: CheckCredit
type: callback
action:
  functionRef:
    refName: callCreditCheckMicroservice
    arguments:
      customer: "${ .customer }"
eventRef: CreditCheckCompletedEvent
timeouts:
  stateExecTimeout: PT15M
transition: EvaluateDecision
----

The Callback state allows you to explicitly model manual decision steps during workflow execution. The `action` property defines a function call that triggers an external activity or service. Once the action executes, the callback state will wait for a CloudEvent, which indicates the completion of the manual decision by the called service.

Once the completion callback event is received, the Callback state completes its execution and transitions to the next defined workflow state or completes workflow execution in case it is an end state.