:_content-type: ASSEMBLY
include::_attributes/common-attributes.adoc[]
[id="serverless-logic-overview"]
= Serverless Logic overview
:context: serverless-logic-overview

toc::[]

Serverless Logic enables developers or architects to define declarative workflow models that orchestrate event-driven, serverless applications.

Serverless Logic is also designed to write workflows in formats (JSON or YAML) that might be better suited for developing and deploying serverless applications in cloud or container environments.

For Serverless Logic implementation, you can use the Kubernetes operator to deploy the workflow models using Knative. Knative Eventing plays an important role and provides the essential infrastructure for event-driven architectures.

// Add additional resources if any

This guide provides a detailed view of the various Serverless Logic concepts.

// modules present in this assembly 

include::modules/serverless-logic-overview-events.adoc[leveloffset=+1]
include::modules/serverless-logic-overview-callbacks.adoc[leveloffset=+1]
include::modules/serverless-logic-overview-jq-expressions.adoc[leveloffset=+1]
include::modules/serverless-logic-overview-error-handling.adoc[leveloffset=+1]